name: C0brA
description: |
        There is an unsolved mystery that a wise young man named `Askee` left for us
        right before he vanished into thin air. He left us a note
        that reads `1071` and `462` are my non-primes, shine away towards the `GCD`,
        `Inverse multiplication` is my jack of trade.

        Can you help us solve this mystery?
category: crypto
flags: 10an{9R347357_C0Mm0n_D1v150R}
author: ZeroC00L
files:
        - "mystery.txt"
