name: Wizard
description: |
    Hi there. The admins on my favorite hacking site have been looking for new elite H4x0rs,
    so they sent everyone on the site a strange binary. They also mentioned something about express `UPS package` delivery.

    Can you help me become an elite H4x0r?
category: re
flags: 10an{h4x02_w1242d_y0u_423}
author: ZeroC00L
hints:
    - hint: I do recall the UPS package thing being a reference to some sort of an executable compression software.
